=== neera17/xml_repo/XmlProject/src/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movies (movie+)>
<!ELEMENT movie (code,title,year-of-release?,theater-name+,city*)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year-of-release (#PCDATA)>
<!ELEMENT theater-name (#PCDATA)>
<!ELEMENT city (#PCDATA)>

=== neera17/xml_repo/XmlProject/src/movieinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "movies.dtd" >
<movies>
  <movie>
    <code>101</code>
    <title>Dil Wale Dulhaniya Le Jayenge</title>
    <year-of-release>1995</year-of-release>
    <theater-name>Maratha Mandir</theater-name>
    <city>Mumbai</city>
  </movie>
  
  <movie>
   <code>102</code>
   <title>Rock On!</title>
   <year-of-release>2008</year-of-release>
   <theater-name>Carnival</theater-name>
   <city>Indore</city>
  </movie>
  
</movies>
